### PR TITLE
Adds action to run ESLint on commit

### PR DESCRIPTION
**Pull request by mattxwang**
This PR:

* adds `npm run lint` to auto-run `eslint` on our source file(s)
* adds `npm run lint-fix` to auto-fix all autofixable errors 
* creates a github action, `lint`, to check if `eslint` succeeds
* changes the eslint env to `node` (from `browser`, which was incorrect)

As a note, there are currently some auto-fixable errors; I have **not** fixed these yet (since they may cause a merge conflict), but I can fix all errors with `npm run lint-fix`.

Debating on whether or not we should merge this first or #28 - @uclaacm/discord-bot-team what do y'all think?

(note: we'll squash this before merging) 

part of #29

### CODE REVIEW

**Review by evanzhong — APPROVED** [review]
lgtm

As for the decision on whether we should merge this first or #28. My 2 cents is we should wait for Brett's PR to merge in first (despite it not being linted) then merge this one and follow-up with a sanitation PR where we run this new lint-workflow on all files.

Thoughts?

**Comment by mattxwang** [comment]
> My 2 cents is we should wait for Brett's PR to merge in first (despite it not being linted) then merge this one and follow-up with a sanitation PR where we run this new lint-workflow on all files.

Seems reasonable to me!

**Comment by mattxwang** [comment]
Just to comment here for posterity - is there a reason why `setMsg` in the `msg.js` file is never used? Is this a mistake from the refactor, or just an incomplete function from earlier? The other error (dotenv not being used) isn't as bad

cc: @entrohpy @Bwoltz

**Comment by Bwoltz** [comment]
@mattxwang I believe that's an issue from the refactor. `setMsg` should be called in `main.js`. I might not have hooked it up correctly.

https://github.com/uclaacm/ACM-at-UCLA-Discord-Bot/blob/4bdf86925b63137bb0afaf25981d9d2ad083a632/main.js#L314

**Comment by entrohpy** [comment]
@Bwoltz @mattxwang sorry I did not catch that in the review! I've exported it and pushed the change.

**Pull request merged**
